
export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAILED = 'AUTH_FAILED'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'


export const AUTH_CHECK_STATE = 'AUTH_CHECK_STATE'

export const PUBLISH_BLOG_START = 'PUBLISH_BLOG_START'
export const PUBLISH_BLOG_SUCCESS = 'PUBLISH_BLOG_SUCCESS'
export const PUBLISH_BLOG_FAILED = 'PUBLISH_BLOG_FAILED'

export const DELETE_USER_BLOG_START = 'DELETE_USER_BLOG_START'
export const DELETE_USER_BLOG_SUCCESS = 'DELETE_USER_BLOG_SUCCESS'
export const DELETE_USER_BLOG_FAILED = 'DELETE_USER_BLOG_FAILED'

export const FETCH_USER_INFO_START = 'FETCH_USER_INFO_START'
export const FETCH_USER_INFO_SUCCESS = 'FETCH_USER_INFO_SUCCESS'
export const FETCH_USER_INFO_FAILED = 'FETCH_USER_INFO_FAILED'

export const FETCH_LATEST_BLOGS_START = 'FETCH_LATEST_BLOGS_START'
export const FETCH_LATEST_BLOGS_SUCCESS = 'FETCH_LATEST_BLOGS_SUCCESS'
export const FETCH_LATEST_BLOGS_FAILED = 'FETCH_LATEST_BLOGS_FAILED'

export const FETCH_BLOGS_START = 'FETCH_BLOGS_START'
export const FETCH_BLOGS_SUCCESS = 'FETCH_BLOGS_SUCCESS'
export const FETCH_BLOGS_FAILED = 'FETCH_BLOGS_FAILED'

export const FETCH_PARTICULAR_BLOG_START = 'FETCH_PARTICULAR_BLOG_START'
export const FETCH_PARTICULAR_BLOG_SUCCESS = 'FETCH_PARTICULAR_BLOG_SUCCESS'
export const FETCH_PARTICULAR_BLOG_FAILED = 'FETCH_PARTICULAR_BLOG_FAILED'

export const FETCH_QUERIED_BLOG_START = 'FETCH_QUERIED_BLOG_START'
export const FETCH_QUERIED_BLOG_SUCCESS = 'FETCH_QUERIED_BLOG_SUCCESS'
export const FETCH_QUERIED_BLOG_FAILED = 'FETCH_QUERIED_BLOG_FAILED'

export const FETCH_USER_LIKED_START = 'FETCH_USER_LIKED_START'
export const FETCH_USER_LIKED_SUCCESS = 'FETCH_USER_LIKED_SUCCESS'
export const FETCH_USER_LIKED_FAILED = 'FETCH_USER_LIKED_FAILED'

export const FETCH_USER_BOOKMARK_START = 'FETCH_USER_BOOKMARK_START'
export const FETCH_USER_BOOKMARK_SUCCESS = 'FETCH_USER_BOOKMARK_SUCCESS'
export const FETCH_USER_BOOKMARK_FAILED = 'FETCH_USER_BOOKMARK_FAILED'

export const ADD_BOOKMARK_START = 'ADD_BOOKMARK_START'
export const ADD_BOOKMARK_SUCCESS = 'ADD_BOOKMARK_SUCCESS'
export const ADD_BOOKMARK_FAILED = 'ADD_BOOKMARK_FAILED'

export const ADD_LIKED_START = 'ADD_LIKED_START'
export const ADD_LIKED_SUCCESS = 'ADD_LIKED_SUCCESS'
export const ADD_LIKED_FAILED = 'ADD_LIKED_FAILED'

export const REMOVE_BOOKMARK_START = 'REMOVE_BOOKMARK_START'
export const REMOVE_BOOKMARK_SUCCESS = 'REMOVE_BOOKMARK_SUCCESS'
export const REMOVE_BOOKMARK_FAILED = 'REMOVE_BOOKMARK_FAILED'

export const REMOVE_LIKED_START = 'REMOVE_LIKED_START'
export const REMOVE_LIKED_SUCCESS = 'REMOVE_LIKED_SUCCESS'
export const REMOVE_LIKED_FAILED = 'REMOVE_LIKED_FAILED'

export const UPDATE_USER_PROFESSION_START = 'UPDATE_USER_PROFESSION_START'
export const UPDATE_USER_PROFESSION_SUCCESS = 'UPDATE_USER_PROFESSION_SUCCESS'
export const UPDATE_USER_PROFESSION_FAILED = 'UPDATE_USER_PROFESSION_FAILED'

export const UPDATE_USER_BIO_START = 'UPDATE_USER_BIO_START'
export const UPDATE_USER_BIO_SUCCESS = 'UPDATE_USER_BIO_SUCCESS'
export const UPDATE_USER_BIO_FAILED = 'UPDATE_USER_BIO_FAILED'

export const UPDATE_USER_IMAGE_START = 'UPDATE_USER_IMAGE_START'
export const UPDATE_USER_IMAGE_SUCCESS = 'UPDATE_USER_IMAGE_SUCCESS'
export const UPDATE_USER_IMAGE_FAILED = 'UPDATE_USER_IMAGE_FAILED'